

on:
  pull_request:
    types:
      - opened


jobs:
  check-hotfix-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up account
        run: |
          git config  user.email "tapish.sinha@remotestate.com"
          git config  user.name "tapishsinha-rs"

      - name: Check for "hotfix" in the last commit
        run: |
          if git log --oneline --grep="init" | sed -E 's/.*\binit\b[^[:alnum:]_]+//'; then
            echo "Hotfix found in the last commit."
            echo "Content " > test.txt
            git add test.txt
            git commit -m "Add github.sh" 
            git push origin ${{ github.event.pull_request.head.ref }}
          else
            echo "No hotfix in the last commit."
          fi
       
