name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
  
          channel-id: 'C04AZ89JHQE'
    # For posting a simple plain text message
          slack-message: "testing slack token"
        env:
           SLACK_BOT_TOKEN: ${{ secrets.TOKEN_TEST }}
