# name: hello-world
# on: push
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello World!"
      
#       - name: Post to a Slack channel
#         id: slack
#         uses: slackapi/slack-github-action@v1.24.0
#         with:
  
#           channel-id: 'C04AZ89JHQE'
#     # For posting a simple plain text message
#           slack-message: "testing slack token"
#         env:
#            SLACK_BOT_TOKEN: ${{ secrets.TOKEN_TEST }}



on:
  push:


jobs:
  check-hotfix-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 777 ~/.ssh/id_rsa
          touch ~/.ssh/config
          cp config ~/.ssh/config
          cat ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub
          
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up account
        run: |
          git config  user.email "vaishnavi.gupta@remotestate.com"
          git config  user.name "vaishnavi-g06"

      - name: Check for "hotfix" in the last commit
        run: |
          if git log --oneline --grep="init" | sed -E 's/.*\binit\b[^[:alnum:]_]+//'; then
            echo "Hotfix found in the last commit."
            echo "Content " > test.txt
            git add test.txt
            git commit -m "Add test
            " 
            git push origin ${{ github.event.pull_request.head.ref }}
          else
            echo "No hotfix in the last commit."
          fi
       

